global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting rules configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api-gateway:3001"]
  
  - job_name: "main-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["main-service:3002"]
  
  - job_name: "feed-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["feed-service:3003"]
  
  - job_name: "message-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["message-service:3004"]
  
  - job_name: "reel-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["reel-service:3005"]
  
  - job_name: "notification-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["notification-service:3006"]
  
  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]
  
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
  
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"] 