apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-service-config
  namespace: microservices
  labels:
    app: iot-service

data:
  MQTT_BROKER_URL: "tcp://mosca:1883"
  MQTT_RAW_TOPIC: "krishi/iot/raw"
  MQTT_SOIL_TOPIC: "krishi/iot/soil"
  MQTT_WEATHER_TOPIC: "krishi/iot/weather"
  CLICKHOUSE_ADDR: "clickhouse:9000"
  CLICKHOUSE_DATABASE: "krishi_iot"
  DEVICE_INTERVAL_SECONDS: "10"
  DEVICE_ID: "krishi-device-001"
