class HomeLocalizations {
  static const Map<String, Map<String, String>> _localized = {
    'en': {
      'hello': 'Hello',
      'welcome': 'Welcome',
      'services': 'Services',
      'quick_access': 'Quick Access',
      'expert_chat': 'Expert Chat',
      'expert_subtitle': 'Talk to farming experts',
      'learn_videos': 'Learn Farming',
      'videos_subtitle': 'Watch tutorial videos',
      'weather': 'Weather',
      'weather_subtitle': 'Check forecast',
      'settings': 'Settings',
      'settings_subtitle': 'App preferences',
      'trending_topics': 'Trending Topics',
      'trending_videos': 'Trending Videos',
      'view_all': 'View All',
      'views': 'views',
      'hot_products': 'Hot Products',
      'new': 'NEW',
      'latest_schemes': 'Government Schemes',
      'learn_more': 'Learn More',
      'active': 'Active',
      'description': 'Description',
      'eligibility': 'Eligibility',
      'benefits': 'Benefits',
      'required_documents': 'Required Documents',
      'close': 'Close',
      'testimonials': 'What Farmers Say',
      'share_app':
          "Share KrishiMantra with more farmers and enjoy our free services. Let's grow with technology together!",
      'advertisement': 'Advertisement',
      'location_disabled': 'Location Service Disabled',
      'enable_location': 'Please enable location services.',
      'permission_denied': 'Permission Denied',
      'allow_location_btn': 'Allow Location',
      'allow_location': 'Please allow location access to use this feature.',
      'permission_denied_forever': 'Permission Denied Forever',
      'go_to_settings':
          'You have denied location permission permanently. Go to settings to enable it.',
      'error_fetching_location': 'Error fetching location',
      'fetching_location': 'Fetching location...',
      'failed_to_load_image': 'Failed to load image',
      'weather_requires_location': 'Weather data requires location',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'clouds': 'Clouds',
      'consultation': 'Consultation',
      'crop_calendar': 'Crop Calendar',
      'companies': 'Companies',
      'fertilizers': 'Fertilizers',
      'krishi_ai': 'Krishi AI',
      'krishi_videos': 'Krishi Videos',
      'marketplace': 'Marketplace',
      'schemes': 'Schemes',
      'measure_farm': 'Measure Farm',
      'fm_enable_location': 'Please enable location services',
      'fm_permission_denied': 'Location permission denied',
      'fm_location_error': 'Error getting location',
      'fm_street_view': 'Street View',
      'fm_satellite_view': 'Satellite View',
      'fm_my_location': 'My Location',
      'fm_undo': 'Undo',
      'fm_clear': 'Clear All',
      'fm_points': 'points',
      'fm_min_points': 'Tap at least 3 points on the map',
      'fm_hectares': 'Hectares',
      'fm_sq_meters': 'Sq Meters',
      'fm_bigha': 'Bigha',
      'fm_guntha': 'Guntha',
      'fm_guide_title': 'Measure Your Farm',
      'fm_guide_body': 'Tap on the satellite map to place boundary points around your farm. Add at least 3 points to see the area.',
      'banner_consultation_subtitle': 'Get expert advice for your farm instantly',
      'banner_measure_subtitle': 'Measure your farm area with pinpoint accuracy',
      // AI Crop Disease Detection
      'dd_title': 'Crop Doctor',
      'dd_camera': 'Take Photo',
      'dd_gallery': 'Upload Image',
      'dd_placeholder': 'Scan for Diseases',
      'dd_placeholder_hint': 'Take a clear photo of the diseased leaf',
      'dd_scanning': 'Analyzing Leaf...',
      'dd_scanning_hint': 'Our AI is identifying the disease',
      'dd_healthy': 'Healthy Plant',
      'dd_confidence': 'Confidence',
      'dd_description': 'What it is',
      'dd_treatment': 'Treatment',
      'dd_prevention': 'Prevention',
      'dd_scan_again': 'Scan New Leaf',
      'dd_recent_scans': 'Recent Scans',
      // Mandi Prices
      'mandi_title': 'Mandi Prices',
      'mandi_search_hint': 'Search crop or market...',
      'mandi_state': 'Select State',
      'mandi_district': 'Select District',
      'mandi_market_price': 'Market Price',
      'mandi_range': 'Price Range',
      'mandi_above_msp': 'Above MSP',
      'mandi_below_msp': 'Below MSP',
      'mandi_no_results': 'No results found',
      'mandi_msp_label': 'Govt MSP',
      'mandi_variety': 'Variety',
      'mandi_grade': 'Grade',
      'mandi_unit': 'Unit',
      'mandi_all_states': 'All States',
      'mandi_all_districts': 'All Districts',
      'mandi_covering': 'Covering',
      'mandi_markets_nationwide': 'Markets Nationwide',
    },
    'hi': {
      'hello': 'नमस्ते',
      'welcome': 'स्वागत है',
      'services': 'सेवाएं',
      'quick_access': 'त्वरित पहुंच',
      'expert_chat': 'विशेषज्ञ से बात',
      'expert_subtitle': 'कृषि विशेषज्ञों से बात करें',
      'learn_videos': 'खेती सीखें',
      'videos_subtitle': 'ट्यूटोरियल वीडियो देखें',
      'weather': 'मौसम',
      'weather_subtitle': 'पूर्वानुमान देखें',
      'settings': 'सेटिंग्स',
      'settings_subtitle': 'ऐप प्राथमिकताएं',
      'trending_topics': 'ट्रेंडिंग विषय',
      'trending_videos': 'ट्रेंडिंग वीडियो',
      'view_all': 'सभी देखें',
      'views': 'व्यूज़',
      'hot_products': 'लोकप्रिय उत्पाद',
      'new': 'नया',
      'latest_schemes': 'सरकारी योजनाएं',
      'learn_more': 'और जानें',
      'active': 'सक्रिय',
      'description': 'विवरण',
      'eligibility': 'पात्रता',
      'benefits': 'लाभ',
      'required_documents': 'आवश्यक दस्तावेज',
      'close': 'बंद करें',
      'testimonials': 'किसानों की राय',
      'share_app':
          'कृषिमंत्रा को ज्यादा किसानों के साथ साझा करें और हमारी मुफ्त सेवाओं का लाभ लें।',
      'advertisement': 'विज्ञापन',
      'location_disabled': 'लोकेशन सेवा बंद है',
      'enable_location': 'कृपया लोकेशन सेवाएं सक्षम करें।',
      'permission_denied': 'अनुमति अस्वीकृत',
      'allow_location_btn': 'लोकेशन अनुमति दें',
      'allow_location': 'कृपया इस फीचर के लिए लोकेशन अनुमति दें।',
      'permission_denied_forever': 'अनुमति स्थायी रूप से अस्वीकृत',
      'go_to_settings':
          'आपने लोकेशन अनुमति स्थायी रूप से अस्वीकृत की है। सेटिंग्स में जाकर सक्षम करें।',
      'error_fetching_location': 'लोकेशन प्राप्त करने में त्रुटि',
      'fetching_location': 'लोकेशन प्राप्त हो रही है...',
      'failed_to_load_image': 'इमेज लोड करने में विफल',
      'weather_requires_location': 'मौसम डेटा के लिए लोकेशन आवश्यक है',
      'temperature': 'तापमान',
      'humidity': 'नमी',
      'clouds': 'बादल',
      'consultation': 'सलाह-मशविरा',
      'crop_calendar': 'क्रॉप कैलेंडर',
      'companies': 'कंपनियां',
      'fertilizers': 'खाद',
      'krishi_ai': 'कृषि एआई',
      'krishi_videos': 'कृषि वीडियो',
      'marketplace': 'बाजारपेठ',
      'schemes': 'योजनाएं',
      'measure_farm': 'खेत नापें',
      'fm_enable_location': 'कृपया लोकेशन सेवाएं सक्षम करें',
      'fm_permission_denied': 'लोकेशन अनुमति अस्वीकृत',
      'fm_location_error': 'लोकेशन प्राप्त करने में त्रुटि',
      'fm_street_view': 'सड़क दृश्य',
      'fm_satellite_view': 'उपग्रह दृश्य',
      'fm_my_location': 'मेरी लोकेशन',
      'fm_undo': 'अंडू करें',
      'fm_clear': 'सब हटाएं',
      'fm_points': 'बिंदु',
      'fm_min_points': 'नक्शे पर कम से कम 3 बिंदु टैप करें',
      'fm_hectares': 'हेक्टेयर',
      'fm_sq_meters': 'वर्ग मीटर',
      'fm_bigha': 'बीघा',
      'fm_guntha': 'गुंठा',
      'fm_guide_title': 'अपना खेत नापें',
      'fm_guide_body': 'अपने खेत की सीमा अंकित करने के लिए सैटेलाइट मैप पर टैप करें। क्षेत्रफल देखने के लिए कम से कम 3 बिंदु जोड़ें।',
      'banner_consultation_subtitle': 'अपने खेत के लिए तुरंत विशेषज्ञ सलाह लें',
      'banner_measure_subtitle': 'सटीक सटीकता के साथ अपने कृषि क्षेत्र को मापें',
      // AI Crop Disease Detection
      'dd_title': 'क्राप डॉक्टर',
      'dd_camera': 'फोटो लें',
      'dd_gallery': 'गैलरी से चुनें',
      'dd_placeholder': 'बीमारी की जांच करें',
      'dd_placeholder_hint': 'रोगग्रस्त पत्ते की साफ फोटो लें',
      'dd_scanning': 'पत्ते का विश्लेषण...',
      'dd_scanning_hint': 'हमारा एआई बीमारी की पहचान कर रहा है',
      'dd_healthy': 'स्वस्थ पौधा',
      'dd_confidence': 'विश्वास',
      'dd_description': 'यह क्या है',
      'dd_treatment': 'उपचार',
      'dd_prevention': 'रोकथाम',
      'dd_scan_again': 'नया पत्ता स्कैन करें',
      'dd_recent_scans': 'हालिया स्कैन',
      // Mandi Prices
      'mandi_title': 'मंडी भाव',
      'mandi_search_hint': 'फसल या मंडी खोजें...',
      'mandi_state': 'राज्य चुनें',
      'mandi_district': 'जिला चुनें',
      'mandi_market_price': 'बाजार भाव',
      'mandi_range': 'मूल्य सीमा',
      'mandi_above_msp': 'MSP से ऊपर',
      'mandi_below_msp': 'MSP से नीचे',
      'mandi_no_results': 'कोई परिणाम नहीं मिला',
      'mandi_msp_label': 'सरकारी MSP',
      'mandi_variety': 'किस्म',
      'mandi_grade': 'ग्रेड',
      'mandi_unit': 'इकाई',
      'mandi_all_states': 'सभी राज्य',
      'mandi_all_districts': 'सभी जिले',
      'mandi_covering': 'समाविष्ट',
      'mandi_markets_nationwide': 'देशव्यापी बाजार',
    },
    'mr': {
      'hello': 'नमस्कार',
      'welcome': 'स्वागत आहे',
      'services': 'सेवा',
      'quick_access': 'द्रुत प्रवेश',
      'expert_chat': 'तज्ञ गप्पा',
      'expert_subtitle': 'शेती तज्ज्ञांशी बोला',
      'learn_videos': 'शेती शिका',
      'videos_subtitle': 'ट्यूटोरियल व्हिडिओ पहा',
      'weather': 'हवामान',
      'weather_subtitle': 'अंदाज तपासा',
      'settings': 'सेटिंग्ज',
      'settings_subtitle': 'अॅप प्राधान्ये',
      'trending_topics': 'ट्रेंडिंग विषय',
      'trending_videos': 'ट्रेंडिंग व्हिडिओ',
      'view_all': 'सर्व पहा',
      'views': 'व्ह्यूज',
      'hot_products': 'लोकप्रिय उत्पादने',
      'new': 'नवे',
      'latest_schemes': 'सरकारी योजना',
      'learn_more': 'अधिक जाणून घ्या',
      'active': 'सक्रिय',
      'description': 'वर्णन',
      'eligibility': 'पात्रता',
      'benefits': 'फायदे',
      'required_documents': 'आवश्यक कागदपत्रे',
      'close': 'बंद करा',
      'testimonials': 'शेतकऱ्यांचे मत',
      'share_app':
          'कृषीमंत्रा अधिक शेतकऱ्यांसोबत शेअर करा आणि मोफत सेवांचा लाभ घ्या.',
      'advertisement': 'जाहिरात',
      'location_disabled': 'लोकेशन सेवा बंद आहे',
      'enable_location': 'कृपया लोकेशन सेवा सुरू करा.',
      'permission_denied': 'परवानगी नाकारली',
      'allow_location_btn': 'लोकेशन परवानगी द्या',
      'allow_location': 'हे फीचर वापरण्यासाठी लोकेशन परवानगी द्या.',
      'permission_denied_forever': 'परवानगी कायमची नाकारली',
      'go_to_settings':
          'तुम्ही लोकेशन परवानगी कायमची नाकारली आहे. सेटिंग्जमध्ये जाऊन सक्षम करा.',
      'error_fetching_location': 'लोकेशन मिळवताना त्रुटी',
      'fetching_location': 'लोकेशन मिळवत आहे...',
      'failed_to_load_image': 'प्रतिमा लोड करण्यात अयशस्वी',
      'weather_requires_location': 'हवामान माहितीसाठी लोकेशन आवश्यक आहे',
      'temperature': 'तापमान',
      'humidity': 'आर्द्रता',
      'clouds': 'ढग',
      'consultation': 'सल्लामसलत',
      'crop_calendar': 'क्रॉप कॅलेंडर',
      'companies': 'कंपन्या',
      'fertilizers': 'खते',
      'krishi_ai': 'कृषी ए.आय',
      'krishi_videos': 'कृषी व्हिडिओ',
      'marketplace': 'बाजारपेठ',
      'schemes': 'योजना',
      'measure_farm': 'शेत मोजा',
      'fm_enable_location': 'कृपया लोकेशन सेवा सुरू करा',
      'fm_permission_denied': 'लोकेशन परवानगी नाकारली',
      'fm_location_error': 'लोकेशन मिळवताना त्रुटी',
      'fm_street_view': 'रस्ता दृश्य',
      'fm_satellite_view': 'उपग्रह दृश्य',
      'fm_my_location': 'माझी लोकेशन',
      'fm_undo': 'मागे घ्या',
      'fm_clear': 'सर्व हटवा',
      'fm_points': 'बिंदू',
      'fm_min_points': 'नकाशावर किमान ३ बिंदू टॅप करा',
      'fm_hectares': 'हेक्टर',
      'fm_sq_meters': 'चौ.मी.',
      'fm_bigha': 'बिघा',
      'fm_guntha': 'गुंठा',
      'fm_guide_title': 'तुमचे शेत मोजा',
      'fm_guide_body': 'तुमच्या शेताची सीमा अंकित करण्यासाठी सॅटेलाइट नकाशावर टॅप करा. क्षेत्रफळ पाहण्यासाठी किमान ३ बिंदू जोडा.',
      'fm_got_it': 'समजले!',
      'fm_banner_subtitle': 'सॅटेलाइट नकाशावरून तुमच्या शेताचे अचूक क्षेत्रफळ मोजा',
      'banner_consultation_subtitle': 'आपल्या शेतीसाठी त्वरित तज्ञांचा सल्ला मिळवा',
      'banner_measure_subtitle': 'निक्कल अचूकतेने आपल्या शेती क्षेत्राचे मोजमाप करा',
      // AI Crop Disease Detection
      'dd_title': 'पीक डॉक्टर',
      'dd_camera': 'फोटो काढा',
      'dd_gallery': 'गॅलरीमधून निवडा',
      'dd_placeholder': 'रोगासाठी स्कॅन करा',
      'dd_placeholder_hint': 'रोगट पानाचा स्पष्ट फोटो घ्या',
      'dd_scanning': 'पानाचे विश्लेषण...',
      'dd_scanning_hint': 'आमचे एआय रोग ओळखत आहे',
      'dd_healthy': 'निरोगी रोप',
      'dd_confidence': 'खात्री',
      'dd_description': 'हे काय आहे',
      'dd_treatment': 'उपचार',
      'dd_prevention': 'प्रतिबंध',
      'dd_scan_again': 'नवीन पान स्कॅन करा',
      'dd_recent_scans': 'अलीकडील स्कॅन',
      // Mandi Prices
      'mandi_title': 'बाजार भाव',
      'mandi_search_hint': 'पीक किंवा बाजार शोधा...',
      'mandi_state': 'राज्य निवडा',
      'mandi_district': 'जिल्हा निवडा',
      'mandi_market_price': 'बाजार दर',
      'mandi_range': 'दर श्रेणी',
      'mandi_above_msp': 'MSP पेक्षा जास्त',
      'mandi_below_msp': 'MSP पेक्षा कमी',
      'mandi_no_results': 'निकाल आढळला नाही',
      'mandi_msp_label': 'शासकीय MSP',
      'mandi_variety': 'वाण',
      'mandi_grade': 'प्रत',
      'mandi_unit': 'एकक',
      'mandi_all_states': 'सर्व राज्ये',
      'mandi_all_districts': 'सर्व जिल्हे',
      'mandi_covering': 'समाविष्ट',
      'mandi_markets_nationwide': 'देशभरातील बाजारपेठा',
    },
    'gu': {
      'hello': 'નમસ્તે',
      'welcome': 'સ્વાગત છે',
      'services': 'સેવાઓ',
      'quick_access': 'ઝડપી ઍક્સેસ',
      'expert_chat': 'નિષ્ણાત ચેટ',
      'expert_subtitle': 'ખેતી નિષ્ણાત સાથે વાત કરો',
      'learn_videos': 'ખેતી શીખો',
      'videos_subtitle': 'ટ્યુટોરીયલ વિડિઓ જુઓ',
      'weather': 'હવામાન',
      'weather_subtitle': 'અનુમાન તપાસો',
      'settings': 'સેટિંગ્સ',
      'settings_subtitle': 'એપ પસંદગીઓ',
      'trending_topics': 'ટ્રેન્ડિંગ વિષયો',
      'trending_videos': 'ટ્રેન્ડિંગ વિડિઓ',
      'view_all': 'બધું જુઓ',
      'views': 'વ્યૂઝ',
      'hot_products': 'હોટ પ્રોડક્ટ્સ',
      'new': 'નવું',
      'latest_schemes': 'સરકારી યોજનાઓ',
      'learn_more': 'વધુ જાણો',
      'active': 'સક્રિય',
      'description': 'વર્ણન',
      'eligibility': 'પાત્રતા',
      'benefits': 'લાભ',
      'required_documents': 'જરૂરી દસ્તાવેજો',
      'close': 'બંધ કરો',
      'testimonials': 'ખેડુતો શું કહે છે',
      'share_app':
          'કૃષિમંત્રાને વધુ ખેડુતો સાથે શેર કરો અને મફત સેવાઓનો લાભ લો.',
      'advertisement': 'જાહેરાત',
      'weather_requires_location': 'હવામાન ડેટા માટે લોકેશન જરૂરી છે',
      'allow_location': 'લોકેશન મંજૂર કરો',
      'temperature': 'તાપમાન',
      'humidity': 'ભેજ',
      'clouds': 'વાદળ',
      'consultation': 'પરામર્શ',
      'crop_calendar': 'ક્રોપ કેલેન્ડર',
      'companies': 'કંપનીઓ',
      'fertilizers': 'ખાતર',
      'krishi_ai': 'કૃષિ AI',
      'krishi_videos': 'કૃષિ વિડિઓ',
      'marketplace': 'માર્કેટપ્લેસ',
      'schemes': 'યોજનાઓ',
      'measure_farm': 'ખેતર માપો',
      'fm_enable_location': 'કૃપા કરી લોકેશન સેવાઓ ચાલુ કરો',
      'fm_permission_denied': 'લોકેશન પરવાનગી નકારાઈ',
      'fm_location_error': 'લોકેશન મેળવવામાં ભૂલ',
      'fm_street_view': 'રસ્તાનું દૃશ્ય',
      'fm_satellite_view': 'ઉપગ્રહ દૃશ્ય',
      'fm_my_location': 'મારું સ્થાન',
      'fm_undo': 'પાછું લો',
      'fm_clear': 'બધું કાઢો',
      'fm_points': 'બિંદુ',
      'fm_min_points': 'નકશા પર ઓછામાં ઓછા ૩ બિંદુ ટેપ કરો',
      'fm_hectares': 'હેક્ટર',
      'fm_sq_meters': 'ચો.મી.',
      'fm_bigha': 'બીઘા',
      'fm_guntha': 'ગુંઠા',
      'fm_guide_title': 'તમારું ખેતર માપો',
      'fm_guide_body': 'તમારા ખેતરની સીમા ચિહ્નિત કરવા સૅટેલાઇટ નકશા પર ટૅપ કરો. વિસ્તાર જોવા ઓછામાં ઓછા ૩ બિંદુ ઉમેરો.',
      'fm_got_it': 'સમજાયું!',
      'fm_banner_subtitle': 'સૅટેલાઇટ નકશાથી તમારા ખેતરનું સાચું ક્ષેત્રફળ માપો',
      'banner_consultation_subtitle': 'તમારા ખેતર માટે તરત જ નિષ્ણાત સલાહ મેળવો',
      'banner_measure_subtitle': 'પિનપોઇન્ટ ચોકસાઈ સાથે તમારા ખેતી વિસ્તારને માપો',
      // AI Crop Disease Detection
      'dd_title': 'ક્રોપ ડોક્ટર',
      'dd_camera': 'ફોટો લો',
      'dd_gallery': 'ગેલેરીમાંથી પસંદ કરો',
      'dd_placeholder': 'રોગની તપાસ કરો',
      'dd_placeholder_hint': 'રોગગ્રસ્ત પાંદડાનો સ્પષ્ટ ફોટો લો',
      'dd_scanning': 'પાંદડાનું વિશ્લેષણ...',
      'dd_scanning_hint': 'અમારું AI રોગની ઓળખ કરી રહ્યું છે',
      'dd_healthy': 'તંદુરસ્ત છોડ',
      'dd_confidence': 'વિશ્વાસ',
      'dd_description': 'આ શું છે',
      'dd_treatment': 'સારવાર',
      'dd_prevention': 'નિવારણ',
      'dd_scan_again': 'નવું પાંદડું સ્કેન કરો',
      'dd_recent_scans': 'તાજેતરના સ્કેન',
      // Mandi Prices
      'mandi_title': 'બજાર ભાવ',
      'mandi_search_hint': 'પાક અથવા બજાર શોધો...',
      'mandi_state': 'રાજ્ય પસંદ કરો',
      'mandi_district': 'જિલ્લો પસંદ કરો',
      'mandi_market_price': 'બજાર ભાવ',
      'mandi_range': 'કિંમત શ્રેણી',
      'mandi_above_msp': 'MSP થી ઉપર',
      'mandi_below_msp': 'MSP થી નીચે',
      'mandi_no_results': 'કોઈ પરિણામ મળ્યું નથી',
      'mandi_msp_label': 'સરકારી MSP',
      'mandi_variety': 'જાત',
      'mandi_grade': 'ગ્રેડ',
      'mandi_unit': 'એકમ',
      'mandi_all_states': 'બધા રાજ્યો',
      'mandi_all_districts': 'બધા જિલ્લાઓ',
      'mandi_covering': 'કવર કરી રહ્યા છીએ',
      'mandi_markets_nationwide': 'દેશભરના બજારો',
    },
    'bn': {
      'hello': 'নমস্কার',
      'welcome': 'স্বাগতম',
      'services': 'সেবা',
      'quick_access': 'দ্রুত অ্যাক্সেস',
      'expert_chat': 'বিশেষজ্ঞ চ্যাট',
      'expert_subtitle': 'কৃষি বিশেষজ্ঞদের সাথে কথা বলুন',
      'learn_videos': 'চাষ শিখুন',
      'videos_subtitle': 'টিউটোরিয়াল ভিডিও দেখুন',
      'weather': 'আবহাওয়া',
      'weather_subtitle': 'পূর্বাভাস দেখুন',
      'settings': 'সেটিংস',
      'settings_subtitle': 'অ্যাপ পছন্দসমূহ',
      'trending_topics': 'ট্রেন্ডিং বিষয়',
      'trending_videos': 'ট্রেন্ডিং ভিডিও',
      'view_all': 'সব দেখুন',
      'views': 'ভিউ',
      'hot_products': 'জনপ্রিয় পণ্য',
      'new': 'নতুন',
      'latest_schemes': 'সরকারি প্রকল্প',
      'learn_more': 'আরও জানুন',
      'active': 'সক্রিয়',
      'description': 'বর্ণনা',
      'eligibility': 'যোগ্যতা',
      'benefits': 'সুবিধা',
      'required_documents': 'প্রয়োজনীয় নথি',
      'close': 'বন্ধ করুন',
      'testimonials': 'কৃষকদের মতামত',
      'share_app':
          'কৃষিমন্ত্রা আরও কৃষকদের সাথে শেয়ার করুন এবং বিনামূল্যের সেবা নিন।',
      'advertisement': 'বিজ্ঞাপন',
      'weather_requires_location': 'আবহাওয়ার ডেটার জন্য লোকেশন প্রয়োজন',
      'allow_location': 'লোকেশন অনুমতি দিন',
      'temperature': 'তাপমাত্রা',
      'humidity': 'আর্দ্রতা',
      'clouds': 'মেঘ',
      'consultation': 'পরামর্শ',
      'crop_calendar': 'ক্রপ ক্যালেন্ডার',
      'companies': 'কোম্পানি',
      'fertilizers': 'সার',
      'krishi_ai': 'কৃষি AI',
      'krishi_videos': 'কৃষি ভিডিও',
      'marketplace': 'মার্কেটপ্লেস',
      'schemes': 'প্রকল্প',
      'measure_farm': 'জমি মাপুন',
      'fm_enable_location': 'অনুগ্রহ করে লোকেশন সেবা চালু করুন',
      'fm_permission_denied': 'লোকেশন অনুমতি প্রত্যাখ্যাত',
      'fm_location_error': 'লোকেশন পেতে সমস্যা',
      'fm_street_view': 'রাস্তার দৃশ্য',
      'fm_satellite_view': 'উপগ্রহ দৃশ্য',
      'fm_my_location': 'আমার অবস্থান',
      'fm_undo': 'পূর্বাবস্থায়',
      'fm_clear': 'সব মুছুন',
      'fm_points': 'বিন্দু',
      'fm_min_points': 'মানচিত্রে কমপক্ষে ৩টি বিন্দু ট্যাপ করুন',
      'fm_hectares': 'হেক্টর',
      'fm_sq_meters': 'বর্গ মিটার',
      'fm_bigha': 'বিঘা',
      'fm_guntha': 'গুণ্ঠা',
      'fm_guide_title': 'আপনার জমি পরিমাপ করুন',
      'fm_guide_body': 'আপনার জমির সীমানা চিহ্নিত করতে স্যাটেলাইট মানচিত্রে ট্যাপ করুন। এলাকা দেখতে কমপক্ষে ৩টি বিন্দু যোগ করুন।',
      'fm_got_it': 'বুঝেছি!',
      'fm_banner_subtitle': 'স্যাটেলাইট মানচিত্র দিয়ে আপনার জমির সঠিক পরিমাপ করুন',
      'banner_consultation_subtitle': 'আপনার খামারের জন্য অবিলম্বে বিশেষজ্ঞের পরামর্শ নিন',
      'banner_measure_subtitle': 'নির্ভুল নির্ভুলতার সাথে আপনার খামার এলাকা পরিমাপ করুন',
      // AI Crop Disease Detection
      'dd_title': 'ক্রপ ডাক্তার',
      'dd_camera': 'ছবি তুলুন',
      'dd_gallery': 'গ্যালারি থেকে নিন',
      'dd_placeholder': 'রোগের জন্য স্ক্যান করুন',
      'dd_placeholder_hint': 'রোগাক্রান্ত পাতার একটি পরিষ্কার ছবি নিন',
      'dd_scanning': 'পাতা বিশ্লেষণ করা হচ্ছে...',
      'dd_scanning_hint': 'আমাদের AI রোগ শনাক্ত করছে',
      'dd_healthy': 'সুস্থ গাছ',
      'dd_confidence': 'নিশ্চয়তা',
      'dd_description': 'এটি কি',
      'dd_treatment': 'চিকিৎসা',
      'dd_prevention': 'প্রতিরোধ',
      'dd_scan_again': 'নতুন পাতা স্ক্যান করুন',
      'dd_recent_scans': 'সাম্প্রতিক স্ক্যান',
      // Mandi Prices
      'mandi_title': 'বাজার দর',
      'mandi_search_hint': 'শস্য বা বাজার খুঁজুন...',
      'mandi_state': 'রাজ্য নির্বাচন করুন',
      'mandi_district': 'জেলা নির্বাচন করুন',
      'mandi_market_price': 'বাজার মূল্য',
      'mandi_range': 'মূল্য পরিসীমা',
      'mandi_above_msp': 'MSP এর উপরে',
      'mandi_below_msp': 'MSP এর নিচে',
      'mandi_no_results': 'কোন ফলাফল পাওয়া যায়নি',
      'mandi_msp_label': 'সরকারি MSP',
      'mandi_variety': 'জাত',
      'mandi_grade': 'গ্রেড',
      'mandi_unit': 'একক',
      'mandi_all_states': 'সব রাজ্য',
      'mandi_all_districts': 'সব জেলা',
      'mandi_covering': 'কভার করছে',
      'mandi_markets_nationwide': 'দেশব্যাপী বাজার',
    },
    'ta': {
      'hello': 'வணக்கம்',
      'welcome': 'வரவேற்கிறோம்',
      'services': 'சேவைகள்',
      'quick_access': 'விரைவு அணுகல்',
      'expert_chat': 'நிபுணர் உரையாடல்',
      'expert_subtitle': 'விவசாய நிபுணர்களுடன் பேசுங்கள்',
      'learn_videos': 'விவசாயம் கற்போம்',
      'videos_subtitle': 'பயிற்சி வீடியோக்களை பாருங்கள்',
      'weather': 'வானிலை',
      'weather_subtitle': 'முன்னறிவிப்பு பார்க்க',
      'settings': 'அமைப்புகள்',
      'settings_subtitle': 'அப் விருப்பங்கள்',
      'trending_topics': 'பிரபல தலைப்புகள்',
      'trending_videos': 'பிரபல வீடியோக்கள்',
      'view_all': 'அனைத்தையும் காண்க',
      'views': 'பார்வைகள்',
      'hot_products': 'பிரபல பொருட்கள்',
      'new': 'புதியது',
      'latest_schemes': 'அரசு திட்டங்கள்',
      'learn_more': 'மேலும் அறிக',
      'active': 'செயலில்',
      'description': 'விளக்கம்',
      'eligibility': 'தகுதி',
      'benefits': 'நன்மைகள்',
      'required_documents': 'தேவையான ஆவணங்கள்',
      'close': 'மூடு',
      'testimonials': 'விவசாயிகள் சொல்வது',
      'share_app':
          'கிரிஷி மந்திராவை மேலும் விவசாயிகளுடன் பகிர்ந்து இலவச சேவைகளை பயன்படுத்துங்கள்.',
      'advertisement': 'விளம்பரம்',
      'weather_requires_location': 'வானிலை தரவிற்கு இடம் அவசியம்',
      'allow_location': 'இடத்தை அனுமதி',
      'temperature': 'வெப்பநிலை',
      'humidity': 'ஈரப்பதம்',
      'clouds': 'மேகங்கள்',
      'consultation': 'ஆலோசனை',
      'crop_calendar': 'பயிர் காலண்டர்',
      'companies': 'நிறுவனங்கள்',
      'fertilizers': 'உரங்கள்',
      'krishi_ai': 'கிரிஷி AI',
      'krishi_videos': 'கிரிஷி வீடியோக்கள்',
      'marketplace': 'மார்க்கெட்ப்ளேஸ்',
      'schemes': 'திட்டங்கள்',
      'measure_farm': 'நிலம் அளவிடு',
      'fm_enable_location': 'இருப்பிட சேவைகளை இயக்கவும்',
      'fm_permission_denied': 'இருப்பிட அனுமதி மறுக்கப்பட்டது',
      'fm_location_error': 'இருப்பிடம் பெறுவதில் பிழை',
      'fm_street_view': 'தெரு காட்சி',
      'fm_satellite_view': 'செயற்கைக்கோள் காட்சி',
      'fm_my_location': 'என் இருப்பிடம்',
      'fm_undo': 'செயல்நீக்கம்',
      'fm_clear': 'அனைத்தையும் அழி',
      'fm_points': 'புள்ளிகள்',
      'fm_min_points': 'வரைபடத்தில் குறைந்தது 3 புள்ளிகளை தட்டவும்',
      'fm_hectares': 'ஹெக்டேர்',
      'fm_sq_meters': 'ச.மீ.',
      'fm_bigha': 'பிகா',
      'fm_guntha': 'குண்டா',
      'fm_guide_title': 'உங்கள் நிலத்தை அளவிடுங்கள்',
      'fm_guide_body': 'உங்கள் நிலத்தின் எல்லையை குறிக்க செயற்கைக்கோள் வரைபடத்தில் தட்டவும். பரப்பளவு காண குறைந்தது 3 புள்ளிகளை சேர்க்கவும்.',
      'fm_got_it': 'புரிந்தது!',
      'fm_banner_subtitle': 'செயற்கைக்கோள் வரைபடம் மூலம் உங்கள் நிலத்தின் பரப்பளவு அளவிடுங்கள்',
      'banner_consultation_subtitle': 'உங்கள் பண்ணைக்காக நிபுணர் ஆலோசனையை உடனடியாகப் பெறுங்கள்',
      'banner_measure_subtitle': 'சரியான துல்லியத்துடன் உங்கள் பண்ணை பகுதியை அளவிடவும்',
      // AI Crop Disease Detection
      'dd_title': 'பயிர் மருத்துவர்',
      'dd_camera': 'புகைப்படம் எடு',
      'dd_gallery': 'கேலரியில் இருந்து எடு',
      'dd_placeholder': 'நோய்களைக் கண்டறியவும்',
      'dd_placeholder_hint': 'பாதிக்கப்பட்ட இலையின் தெளிவான படத்தை எடுக்கவும்',
      'dd_scanning': 'இலை ஆய்வு செய்யப்படுகிறது...',
      'dd_scanning_hint': 'எங்கள் AI நோயைக் கண்டறிகிறது',
      'dd_healthy': 'ஆரோக்கியமான செடி',
      'dd_confidence': 'நம்பிக்கை',
      'dd_description': 'அது என்ன',
      'dd_treatment': 'சிகிச்சை',
      'dd_prevention': 'தடுப்பு முறை',
      'dd_scan_again': 'புதிய இலையை ஸ்கேன் செய்',
      'dd_recent_scans': 'சமீபத்திய ஸ்கேன்கள்',
      // Mandi Prices
      'mandi_title': 'சந்தை விலை',
      'mandi_search_hint': 'பயிர் அல்லது சந்தையைத் தேடு...',
      'mandi_state': 'மாநிலத்தைத் தேர்ந்தெடு',
      'mandi_district': 'மாவட்டத்தைத் தேர்ந்தெடு',
      'mandi_market_price': 'சந்தை விலை',
      'mandi_range': 'விலை வரம்பு',
      'mandi_above_msp': 'MSP-க்கு மேல்',
      'mandi_below_msp': 'MSP-க்கு கீழ்',
      'mandi_no_results': 'முடிவுகள் எதுவும் இல்லை',
      'mandi_msp_label': 'அரசு MSP',
      'mandi_variety': 'வகை',
      'mandi_grade': 'தரம்',
      'mandi_unit': 'அலகு',
      'mandi_all_states': 'அனைத்து மாநிலங்கள்',
      'mandi_all_districts': 'அனைத்து மாவட்டங்கள்',
      'mandi_covering': 'உள்ளடக்கியது',
      'mandi_markets_nationwide': 'நாடு தழுவிய சந்தைகள்',
    },
  };

  static String text(String key, String languageCode) {
    final code = languageCode.isEmpty ? 'en' : languageCode;
    return _localized[code]?[key] ?? _localized['en']?[key] ?? key;
  }
}
