apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
      - name: main-service
        image: your-registry/main-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        envFrom:
        - configMapRef:
            name: main-service-config
        - secretRef:
            name: main-service-secret
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 20
          periodSeconds: 30