apiVersion: apps/v1
kind: Deployment
metadata:
  name: reel-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reel-service
  template:
    metadata:
      labels:
        app: reel-service
    spec:
      containers:
      - name: reel-service
        image: your-registry/reel-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        envFrom:
        - configMapRef:
            name: reel-service-config
        - secretRef:
            name: reel-service-secret
        readinessProbe:
          httpGet:
            path: /reels
            port: 3005
          initialDelaySeconds: 10
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /reels
            port: 3005
          initialDelaySeconds: 20
          periodSeconds: 30