apiVersion: v1
kind: Secret
metadata:
  name: feed-service-secret
  namespace: default
type: Opaque
data:
  # These values need to be base64 encoded before deployment
  # Example: echo -n "your_value" | base64
  MONGODB_URI: <base64-encoded-mongodb-uri>
  JWT_SECRET: <base64-encoded-jwt-secret>
  CLOUDINARY_API_KEY: <base64-encoded-api-key>
  CLOUDINARY_API_SECRET: <base64-encoded-api-secret>
  EMAIL_PASS: <base64-encoded-email-password>
  REDIS_PASSWORD: <base64-encoded-redis-password> 