apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: microservices
data:
  NODE_ENV: "production"
  PORT: "3001"
  MAIN_SERVICE_URL: "http://main-service"
  MESSAGE_SERVICE_URL: "http://message-service"
  FEED_SERVICE_URL: "http://feed-service"
  REEL_SERVICE_URL: "http://reel-service"
  NOTIFICATION_SERVICE_URL: "http://notification-service"